name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # main 브랜치에 새 파일이 들어오면 작동 시작

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v4

      - name: Node.js 환경 설정
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 패키지 설치
        run: npm install

      - name: 웹사이트 빌드
        run: npm run build

      - name: gh-pages 브랜치로 자동 배포
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
